server:
  port: 8080
#  servlet:
#    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: hahan
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  signerKey: "ed3ywfmeCHi39mBwk76SNy+hJAMQA+9P1Irg8J+zV/hne3tfHytmC1G74lQWg4aF"